ngrok:
  # Optional parameters
  #subdomain: alex # reserved tunnel name https://alex.ngrok.io
  #region: us # one of ngrok regions (us, eu, au, ap), defaults to us

telegram:
  chat_ids:
    - 12345
    # - 12346
  message: "The ngrok URL for {proto} on port {port} is: {url}"
